name: Run unit tests
on: [push]

jobs:
  docker_base_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run unit tests
        run: docker build . --file docker/unittest.dockerfile --tag unittest
        env:
          ENABLE_SLOW_TESTS: True

  ubuntu_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up R 4.3.3
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.3'
    - name: Install R development packages
      run: |
        sudo apt-get update
        sudo apt-get install -y r-base-dev
    - name: Install renv and restore R packages
      run: |
        R -e "install.packages('renv', repos='https://cloud.r-project.org/')"
        R -e "renv::restore()"
    - name: Install poetry
      run: pipx install poetry

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Install dependencies
      run: |
        poetry install --with dev
        poetry build
    - name: Running the tests with pytest
      run: poetry run pytest
